controllers:
    resource: ../../src/Controller/
    type: annotation
    requirements:
        UserType: 'student|teacher|admin|owner'

kernel:
    resource: ../../src/Kernel.php
    type: annotation
